replicaCount: 3

namespace: test

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  fsGroup: 1001
  supplementalGroups:
    - 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

service:
  name: test-service
  port: 80
  targetPort: 8080

ingress:
  name: test-ingress
  hostname: test.com
