name: Dependent Workflow

on:
  workflow_run:
    workflows: ["Create a release and build and push Helm Chart"]
    types:
      - completed

jobs:
  dependent_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run dependent task
        run: echo "This runs after the first workflow has finished."
