name: Auto Assign Creator

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue/PR creator
        uses: actions-assign/assign@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
