name: Create dev build

on:
  workflow_dispatch:

jobs:
  create_dev_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Dispatch event to create dev build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: JTaeuber/test-chart
          event-type: create-dev-build
          client-payload: '{"version": "dev"}'
