name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Chart Version
        id: chart_version
        run: |
          version=$(yq e '.version' ./test-chart/Chart.yaml)
          echo "version=v$version" >> $GITHUB_OUTPUT

      - name: Get latest Git tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: End Workflow if version didn't change
        if: steps.get_latest_tag.outputs.latest_tag == steps.chart_version.outputs.version
        id: end_workflow
        run: |
          echo "The version hasn't changed. Cancelling workflow..."
          node -e "require('@actions/core').cancel('Cancelling the workflow because version did not change.')"

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.chart_version.outputs.version }}
          name: ${{ steps.chart_version.outputs.version }}
          generateReleaseNotes: true
