name: Build and Push Helm Package

on:
  push:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Download the tag_flag artifact
        uses: actions/download-artifact@v3
        with:
          name: tag_flag
          path: ./status

      - name: Check if flag is set
        id: check_flag
        run: |
          status=$(cat ./status/tag_flag.txt | grep "flag=true")
          if [ -z "$status" ]; then
            echo "The flag is not set."
            exit 0
          else
            echo "The flag is set. Building helm chart."
          fi

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Log in to Helm OCI Registry
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          helm registry login ${MTR} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          MTR: mtr.devops.telekom.de

      - name: Helm Lint, Package, and Push
        run: |
          cd test-chart
          helm lint .
          helm package .
          helm push $(ls *.tgz | head -1) oci://ghcr.io/jtaeuber/charts
          helm push $(ls *.tgz | head -1) oci://${MTR}/${REPO}/charts
        env:
          MTR: mtr.devops.telekom.de
          REPO: ${{secrets.REPO}}

      - name: Extract Chart Version
        id: chart_version
        run: |
          version=$(yq e '.version' ./test-chart/Chart.yaml)
          echo "version=v$version" >> $GITHUB_OUTPUT

      - name: Dispatch Event to Helm-Charts Repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: jtaeuber/helm-charts
          event-type: new-helm-chart-version
          client-payload: '{"chart": "test-chart", "version": "${{ steps.chart_version.outputs.version }}"}'
