name: Build and push helm chart

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      appVersion:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      REPO:
        required: true
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Log in to Helm OCI Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          echo ${DOCKER_PASSWORD} | helm registry login ${MTR} -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MTR: mtr.devops.telekom.de

      - name: Helm Lint, Package, and Push
        run: |
          cd test-chart
          helm lint .
          helm package . --version ${{ inputs.version }} --app-version ${{ inputs.appVersion }}
          helm push $(ls *.tgz | head -1) oci://ghcr.io/jtaeuber/charts
          helm push $(ls *.tgz | head -1) oci://${MTR}/${REPO}/charts
        env:
          MTR: mtr.devops.telekom.de
          REPO: ${{ secrets.REPO }}

      - name: Dispatch Event to Helm-Charts Repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: JTaeuber/helm-charts
          event-type: new-helm-chart-version
          client-payload: '{"chart": "test-chart", "version": "${{ inputs.version }}"}'
