name: Test Workflow

on:
  workflow_run:
    workflows: ["Create a release and build and push Helm Chart"]
    types:
      - completed

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the Git Tag
        run: 'echo "Git tag: ${GITHUB_REF##*/}"'
