name: Test Workflow

on:
  workflow_run:
    workflows: [Create a release and build and push Helm Chart]
    types:
      - completed

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest Git tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "No tags found")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Check Version Format in Tag
        if: startsWith(${{ env.latest_tag }}, 'refs/tags/v')
        uses: nowsprinting/check-version-format-action@v4.0.2
        id: check-version
        with:
          prefix: "v"

      - name: Set tag
        id: set-tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TAG1="dev"
          TAG2="commit-$SHORT_SHA"

          if [[ "${{ steps.check-version.outputs.is_valid }}" == 'true' ]]; then
            TAG1="latest"
            TAG2="${{ env.latest_tag }}"
          fi

          echo "$TAG1"
          echo "$TAG2"
